name: pneumonia-api
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.19=hbb43b14_0
  - packaging=25.0=py310haa95532_1
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.2.25
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - fastapi==0.133.1
      - filelock==3.24.3
      - fonttools==4.61.1
      - fpdf==1.7.2
      - fsspec==2026.2.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grad-cam==1.5.5
      - h11==0.16.0
      - hf-xet==1.3.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.5.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - narwhals==2.17.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.13.0.92
      - pandas==2.3.3
      - pillow==12.1.1
      - protobuf==6.33.5
      - pyarrow==23.0.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.3.3
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - starlette==0.52.1
      - streamlit==1.54.0
      - sympy==1.14.0
      - tenacity==9.1.4
      - threadpoolctl==3.6.0
      - timm==1.0.25
      - toml==0.10.2
      - torch==2.10.0
      - torchvision==0.25.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - ttach==0.0.3
      - typer==0.24.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.41.0
      - watchdog==6.0.0
prefix: D:\Miniconda\envs\pneumonia-api
